# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    guzzle.client:
        class: GuzzleHttp\Client
        
    App\Service\CompanySymbolService\Client\CompanySymbolClient:
        class: App\Service\CompanySymbolService\Client\CompanySymbolClient
        arguments:
            $client: '@guzzle.client'
            
    App\Service\HistoricalQuotesService\Client\HistoricalQuotesClient:
        class: App\Service\HistoricalQuotesService\Client\HistoricalQuotesClient
        arguments:
            $client: '@guzzle.client'
            $apiKey: '%env(X_RAPID_API_KEY)%'
            $apiHost: '%env(X_RAPID_API_HOST)%'
            
    company.symbol.reader:
        class: App\Service\CompanySymbolService\Reader\CompanyReader        
            
    company.symbol.reader.wrapper:
        class: App\Service\CompanySymbolService\Reader\CompanyReaderWrapper
        arguments:
            $reader: '@company.symbol.reader'
            
    company.symbol.db.reader:
        class: App\Service\CompanySymbolService\Reader\DbCompanyReader
        arguments:
            $reader: '@company.symbol.reader.wrapper'
        
    App\Service\CompanySymbolService\Reader\CompanyReaderInterface: '@company.symbol.db.reader'
        
    
